spring:
  application:
    name: urim-ai-agent
  profiles:
    active: local
server:
  port: 8123  # 端口
  servlet:
    context-path: /api   # 接口前缀
# springdoc-openapi
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.urim.urimaiagent.controller
knife4j:
  enable: true
  setting:
    language: zh_cn
#logging:
#  level:
#    org.springframework.ai.chat.client.advisor.SimpleLoggerAdvisor: debug